### ISSUE TITLE
Missing cvtype function

### ISSUE THREAD

**Issue by ohines** [davidahirshberg/amlinear#1]
Hi David and Stefan,
I was trying to run the example in the `README.md` file.
It seems the function `cvtype` is missing.
This function is called on line 29 of `R/crossfit.cv.glmnet.R`

**Comment by ohines** [comment]
I think the issue is in calling internal glmnet functions

**Comment by davidahirshberg** [comment]
Yeah, sorry about that.  It relies on glmnet internals that have changed
since the package was last updated. One option is to track down the right
version of glmnet. I don't know it off the top of my head, but we can
probably figure it out. Another is to replace the rlasso call, which uses
those out of date internals, with analogous calls using the `rlearner' or `grf' packages.

I'm happy to talk through the options. A few questions:
1. Are you looking to compare something to AMLE in a simulation study or to apply the method?
2. Do you have binary treatment or continuous-valued?
3. What are your covariates like?

**Comment by mlamlamla** [comment]
Hi! Having the same problem here. Could you provide the requirements/which version of glmnet you are using? (in case, that's the issue) I am trying to run the following command:

`glmnet.fit.propensity = amlinear:::crossfit.cv.glmnet(Xmod.int, Wmod, family = "binomial")`

PS: Running

`library(glmnet)`
`help(cvtype)`

in the same environment perfectly works and opens the help file for cvtype.

**Comment by davidahirshberg** [comment]
Mind trying the version that was on CRAN on 12 Apr 2018, the date of the first arXiv posting including those simulations, and letting me know if it works?

**Comment by mlamlamla** [comment]
Thanks for the hint! However, I don't even succeed installing this version of glmnet :/ - 

I tried directly

`remove.packages("glmnet")`
`packageurl <- "https://cran.r-project.org/src/contrib/Archive/glmnet/glmnet_2.0-16.tar.gz"`
`install.packages(packageurl, repos=NULL, type="source")`

but end up not having any glmnet in the end/installation command is ignored.

Alternatively, I tried downloading 2.0-13, 2.0-16, and 2.0-18 directly (downloaded from here: https://cran.r-project.org/src/contrib/Archive/glmnet/), but get unpromising errors:

`devtools::install("~/Downloads/glmnet")`

✔  checking for file ‘~/Downloads/glmnet/DESCRIPTION’
─  preparing ‘glmnet’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  running ‘cleanup’
E  checking vignette meta-information
   Output(s) listed in ‘build/vignette.rds’ but not in package:
     ‘inst/doc/glmnet_beta.pdf’
     ‘inst/doc/Coxnet.pdf’
   Run R CMD build without --no-build-vignettes to re-create

Error in (function (command = NULL, args = character(), error_on_status = TRUE, : System command 'R' failed, exit status: 1, stdout + stderr:

**Comment by davidahirshberg** [comment]
Were you using an April 2018 version of R? It seems like it could be that
or it could be that the dependencies of glmnet aren't specified tightly
enough that old versions of glmnet install properly, so you'd need to force
the installation of old versions of those as well.

**Comment by mlamlamla** [comment]
Yes, that is probably the case. Would you maybe have a requirements.txt for the R environment in which the package would function properly?

**Comment by davidahirshberg** [comment]
I do not.

**Comment by vincent27hugh** [comment]
I ran into the same problem. Still can not figure out how to solve this...
Here is the environment info:

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

...
other attached packages:
amlinear_0.0.0.9000
...
glmnet_4.1-3
```

**Comment by davidahirshberg** [comment]
Hopefully this has been resolved by the comments added to the Readme.
